const personalInfo = {
  name: "Anay Sinhal",
  title: "Clinical AI Researcher & Software Engineer",
  email: "sinhal.anay@ufl.edu",
  mobile: "+1 (352) 219-5579",
  orcid: "0009-0008-8328-2336",

  github: "https://github.com/anayy09",
  linkedin: "https://linkedin.com/in/anaysinhal",
  blog: "https://anay09.hashnode.dev/",
  cv: "/cv",

  description: "Clinical AI researcher and software engineer building health data infrastructure at the University of Florida. My work spans EHR time-series modeling, multimodal clinical representation learning, and reproducible biomedical pipelines on HPC. Seven peer-reviewed publications, three patents, and a Gold Medal in CS.",

  about: {
    intro: "I work at the intersection of clinical informatics, machine learning, and systems engineering. At UF's PRISMAp Lab, I build infrastructure that connects social determinants of health with clinical outcomes — pipelines that run on HiPerGator, models that explain their reasoning, systems that hold up under the pressure of real hospital data.",
    pillars: [
      {
        id: "clinical-ai",
        label: "// clinical.ai",
        title: "Clinical AI & Health Data",
        description: "EHR time-series modeling, AKI phenotyping, SDoH linkage pipelines (SVI, ADI, SDI, EJI), pathology de-identification, explainable AI with SHAP and Grad-CAM. Infrastructure built to run at HPC scale.",
        accent: "teal",
      },
      {
        id: "systems",
        label: "// systems.eng",
        title: "Systems & Infrastructure",
        description: "Full-stack systems from FastAPI microservices to React dashboards, containerized with Docker, scheduled on SLURM. PostgreSQL, Redis, Azure, HiPerGator. Built for correctness before speed.",
        accent: "blue",
      },
      {
        id: "research",
        label: "// research.pub",
        title: "Research & Publications",
        description: "Seven peer-reviewed papers across IEEE, Springer, and Journal of Carcinogenesis. Three Indian patents. Research spans depression detection, polyp segmentation, P2P resilience, and stress monitoring.",
        accent: "lavender",
      },
    ],
  },

  skills: [
    "Clinical AI Researcher",
    "Software Engineer",
    "Health Data Engineer",
    "Systems Builder",
  ],

  techStack: [
    { name: "Python", url: "https://www.python.org" },
    { name: "Go", url: "https://go.dev" },
    { name: "TypeScript", url: "https://www.typescriptlang.org" },
    { name: "JavaScript", url: "https://developer.mozilla.org/docs/Web/JavaScript" },
    { name: "Java", url: "https://www.java.com" },
    { name: "C++", url: "https://isocpp.org" },
    { name: "React", url: "https://react.dev" },
    { name: "Next.js", url: "https://nextjs.org" },
    { name: "FastAPI", url: "https://fastapi.tiangolo.com" },
    { name: "Django", url: "https://www.djangoproject.com" },
    { name: "Node.js", url: "https://nodejs.org" },
    { name: "Spring Boot", url: "https://spring.io/projects/spring-boot" },
    { name: "PyTorch", url: "https://pytorch.org" },
    { name: "TensorFlow", url: "https://www.tensorflow.org" },
    { name: "Hugging Face", url: "https://huggingface.co" },
    { name: "scikit-learn", url: "https://scikit-learn.org" },
    { name: "PostgreSQL", url: "https://www.postgresql.org" },
    { name: "MongoDB", url: "https://www.mongodb.com" },
    { name: "Redis", url: "https://redis.io" },
    { name: "Docker", url: "https://www.docker.com" },
    { name: "Azure", url: "https://azure.microsoft.com" },
    { name: "AWS", url: "https://aws.amazon.com" },
    { name: "SLURM", url: "https://slurm.schedmd.com" },
    { name: "Git", url: "https://git-scm.com" },
    { name: "Figma", url: "https://www.figma.com" },
  ],

  skillCategories: [
    {
      id: "languages",
      label: "// lang",
      title: "Languages",
      skills: [
        { name: "Python", icon: "SiPython" },
        { name: "Go", icon: "SiGo" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "JavaScript", icon: "SiJavascript" },
        { name: "Java", icon: "FaJava" },
        { name: "C/C++", icon: "SiCplusplus" },
        { name: "SQL", icon: "SiPostgresql" },
        { name: "Bash", icon: "SiGnubash" },
      ],
    },
    {
      id: "ml-systems",
      label: "// ml.systems",
      title: "ML & Systems",
      skills: [
        { name: "PyTorch", icon: "SiPytorch" },
        { name: "TensorFlow", icon: "SiTensorflow" },
        { name: "Hugging Face", icon: "SiHuggingface" },
        { name: "scikit-learn", icon: "SiScikitlearn" },
        { name: "FastAPI", icon: "SiFastapi" },
        { name: "Django", icon: "SiDjango" },
        { name: "Spring Boot", icon: "SiSpringboot" },
        { name: "Node.js", icon: "SiNodedotjs" },
        { name: "React", icon: "SiReact" },
        { name: "Next.js", icon: "SiNextdotjs" },
      ],
    },
    {
      id: "infra",
      label: "// infra.data",
      title: "Infrastructure & Data",
      skills: [
        { name: "PostgreSQL", icon: "SiPostgresql" },
        { name: "MongoDB", icon: "SiMongodb" },
        { name: "Redis", icon: "SiRedis" },
        { name: "Docker", icon: "SiDocker" },
        { name: "Azure", icon: "SiMicrosoftazure" },
        { name: "AWS", icon: "SiAmazonaws" },
        { name: "SLURM/HPC", icon: "SiLinux" },
        { name: "Git", icon: "SiGit" },
        { name: "Figma", icon: "SiFigma" },
      ],
    },
  ],

  education: [
    {
      title: "Master's in Computer Science",
      organization: "University of Florida",
      logoUrl: "/logos/uf.png",
      description: "Graduate research in clinical AI and health informatics. Coursework: Advanced Data Structures, Networks, Algorithms, Distributed Systems, Data Science.",
      startDate: "Jan 2025",
      endDate: "Dec 2026",
      skills: ["Adv Data Structures", "Networks", "Algorithms", "Distributed Systems", "Data Science"],
    },
    {
      title: "Semester Exchange",
      organization: "IIT Kanpur",
      logoUrl: "/logos/iitk.png",
      description: "Sixth semester exchange. Coursework in Big Data systems.",
      startDate: "Jan 2024",
      endDate: "May 2024",
      skills: ["Big Data", "Brand Management", "Marketing"],
    },
    {
      title: "Semester Exchange",
      organization: "IIT Gandhinagar",
      logoUrl: "/logos/iitgn.png",
      description: "Third semester exchange.",
      startDate: "Aug 2022",
      endDate: "Dec 2022",
      skills: ["Theory of Computation", "Data Structures", "Philosophy"],
    },
    {
      title: "Bachelor's in Computer Science",
      organization: "JK Lakshmipat University",
      logoUrl: "/logos/jklu.png",
      description: "Gold Medal — Best Outgoing Student in B.Tech CSE, 2025.",
      startDate: "Aug 2021",
      endDate: "May 2025",
      skills: ["Algorithms", "OS", "Machine Learning"],
      award: "Gold Medal — Best Outgoing Student",
    },
  ],

  experience: [
    {
      title: "Graduate Student Assistant",
      organization: "PRISMAp Lab, UF IC3",
      logoUrl: "/logos/ic3.png",
      description: "Building SDoH linkage pipelines integrating SVI, ADI, SDI, and EJI indices with clinical EHR data. Developing AKI phenotyping systems, pathology slide de-identification tools (ResNet + PaddleOCR), and HPC biomedical workflows on HiPerGator (SLURM) and Azure.",
      startDate: "Sep 2025",
      endDate: "Dec 2026",
      location: "Gainesville, FL",
      skills: ["Python", "SLURM", "Azure", "PyTorch", "FastAPI", "PostgreSQL"],
    },
    {
      title: "Research Assistant",
      organization: "IIIT Delhi",
      logoUrl: "/logos/iiitd.png",
      description: "Optimized algorithms for medical image enhancement in the SBI Lab. Signal processing and biomedical imaging pipelines.",
      startDate: "Sep 2024",
      endDate: "Oct 2024",
      location: "New Delhi",
      skills: ["Signal Processing", "Biomedical Imaging", "Python"],
    },
    {
      title: "SDE Intern",
      organization: "GeeksforGeeks",
      logoUrl: "/logos/gfg.png",
      description: "Built and optimized interactive learning modules using Next.js and React. Improved SEO performance and reduced load time across high-traffic pages.",
      startDate: "May 2024",
      endDate: "Sep 2024",
      location: "Noida",
      skills: ["Next.js", "React", "PHP", "SEO"],
    },
    {
      title: "Research Intern",
      organization: "SVNIT Surat",
      logoUrl: "/logos/svnit.png",
      description: "Enhanced depression detection model using contrastive learning over social media text embeddings. Co-authored IEEE publication.",
      startDate: "May 2024",
      endDate: "Jul 2024",
      location: "Hybrid",
      skills: ["Contrastive Learning", "NLP", "PyTorch"],
    },
    {
      title: "Research Intern",
      organization: "IIT Jammu",
      logoUrl: "/logos/iitjmu.png",
      description: "Developed ML models for stress prediction using physiological sensor data. Built ensemble framework using Random Forest and neural networks on wearable sensor datasets.",
      startDate: "Dec 2023",
      endDate: "Jan 2024",
      location: "Remote",
      skills: ["Machine Learning", "Random Forest", "Neural Networks"],
    },
    {
      title: "SDE Intern",
      organization: "Dexpert Systems",
      logoUrl: "/logos/dexpert.png",
      description: "Built ReactJS applications and integrated Zoho CRM with backend systems using Spring Boot and Laravel.",
      startDate: "Jun 2023",
      endDate: "Jul 2023",
      location: "Pune",
      skills: ["React", "Spring Boot", "Zoho CRM", "Laravel"],
    },
  ],

  customProjects: [
    {
      id: "ehr-timeline-triage",
      name: "EHR Timeline Triage",
      description: "Converts longitudinal EHR events into 4-hour binned timelines and trains Logistic Regression, GRU, and Transformer models for 30-day readmission and 48-hour ICU mortality prediction. FastAPI inference service with Next.js dashboard, SHAP feature attribution, and synthetic EHR data generator.",
      url: "https://github.com/anayy09/EHR-Timeline-Triage",
      homepage: "",
      language: "Python",
      domain: "health",
      topics: ["pytorch", "fastapi", "nextjs", "ehr", "clinical-ai"],
      isManual: true,
      imageUrl: "/projects/ehr.png",
    },
    {
      id: "medlyze",
      name: "Medlyze",
      description: "Next.js 15 + PostgreSQL web platform with AES-256 encrypted medical report intake, regex-based de-identification, and role-based access. Multimodal analysis across PDFs and images using LLM and vision models, with longitudinal biomarker tracking and risk scoring views.",
      url: "https://github.com/anayy09/Medlyze",
      homepage: "",
      language: "TypeScript",
      domain: "health",
      topics: ["nextjs", "postgresql", "llm", "healthcare"],
      isManual: true,
      imageUrl: "/projects/medlyze.png",
    },
    {
      id: "radiology-copilot",
      name: "Radiology Copilot",
      description: "Full-stack radiology decision support platform. Multimodal CLIP-style model combining ViT image encoder and ClinicalBERT text encoder to classify 14 chest X-ray findings, with Grad-CAM saliency overlays and calibrated uncertainty. GPU-backed ML microservice, Express API gateway, PostgreSQL study store, AI-drafted radiology reports.",
      url: "https://github.com/anayy09/Radiology-Copilot",
      homepage: "",
      language: "Python",
      domain: "health",
      topics: ["pytorch", "monai", "fastapi", "nextjs", "healthcare"],
      isManual: true,
      imageUrl: "/projects/radiology.png",
    },
    {
      id: "sepsis-sentinel",
      name: "Sepsis Sentinel",
      description: "Sepsis detection system using XGBoost and LightGBM trained on EHR data. AUROC 0.89. FastAPI inference service and React dashboard for real-time risk scores, enabling up to 4-hour earlier alerts in simulation.",
      url: "https://github.com/anayy09/Sepsis-Sentinel",
      homepage: "",
      language: "Python",
      domain: "health",
      topics: ["fastapi", "xgboost", "react", "healthcare"],
      isManual: true,
      imageUrl: "/projects/sepsis.png",
    },
    {
      id: "finmate",
      name: "FinMate",
      description: "Django backend with Plaid API integration, Random Forest forecasting, and Isolation Forest anomaly detection. React + Chakra UI dashboard with D3/Plotly charts and personalized budget alerts.",
      url: "https://github.com/anayy09/Finmate",
      homepage: "",
      language: "Python",
      domain: "systems",
      topics: ["django", "react", "ml", "finance"],
      isManual: true,
      imageUrl: "/projects/finmate.png",
    },
    {
      id: "local-news-analytics",
      name: "Local News Analytics",
      description: "End-to-end NLP pipeline using spaCy, BERTopic, and BART to cluster 2k+ news items daily and flag emerging events. F1 score 0.83. Flask dashboard with scheduled monitoring.",
      url: "https://github.com/anayy09/Local-News-Analytics",
      homepage: "",
      language: "Python",
      domain: "nlp",
      topics: ["nlp", "spacy", "flask", "bert"],
      isManual: true,
      imageUrl: "/projects/news.png",
    },
  ],

  publications: [
    {
      id: "pub-quantum",
      title: "High-Performance Computing for Cancer Drug Interaction Modeling Using Quantum-Classical Hybrid Algorithms",
      authors: ["Banga et al."],
      journal: "International Journal of Advanced Science and Innovation (IJASIS)",
      year: "Feb 2026",
      description: "Quantum-classical hybrid algorithm for modeling cancer drug interactions on HPC infrastructure.",
      status: "Published",
      type: "Journal",
      domain: "Clinical AI",
      url: "",
    },
    {
      id: "pub-stress",
      title: "Stress Monitoring in Healthcare: An Ensemble Machine Learning Framework Using Wearable Sensor Data",
      authors: [""],
      journal: "5th International Conference on Innovations in Computational Intelligence & Computer Vision (ICICV 2026)",
      year: "Feb 2026",
      description: "Multimodal dataset and ensemble ML framework for stress monitoring using wearable sensors, improving predictive accuracy and class balance.",
      status: "Accepted",
      type: "Conference",
      domain: "Clinical AI",
      url: "https://doi.org/10.48550/arXiv.2507.07589",
    },
    {
      id: "pub-facial",
      title: "Artificial Intelligence-Based Facial Recognition for Attendance Management",
      authors: ["Devra et al."],
      journal: "IEEE International Conference on Medical Conditions (MEDCOM 2025)",
      year: "Dec 2025",
      description: "AI-driven facial recognition system for automated attendance management in institutional settings.",
      status: "Published",
      type: "Conference",
      domain: "Systems",
      url: "",
    },
    {
      id: "pub-depression",
      title: "Contrastive Learning and Large Language Models for Depression Detection from Social Media",
      authors: [""],
      journal: "2025 IEEE International Conference on Contemporary Computing & Communications (InC4 2025)",
      year: "Dec 2025",
      description: "Contrastive learning with LLMs for depression detection on social media, achieving improved precision, recall, and F1 scores.",
      status: "Published",
      type: "Conference",
      domain: "NLP",
      url: "https://doi.org/10.1109/InC465408.2025.11256322",
    },
    {
      id: "pub-p2p",
      title: "Battery-Aware Super-Peer and Fountain Coding in Java P2P Systems",
      authors: [""],
      journal: "Discover Internet of Things (Springer)",
      year: "Nov 2025",
      description: "Enhances BitTorrent with battery-aware super-peer selection and fountain coding for improved resilience in disaster scenarios.",
      status: "Published",
      type: "Journal",
      domain: "Systems",
      url: "https://doi.org/10.1007/s43926-025-00240-3",
    },
    {
      id: "pub-diagnostic",
      title: "Optimizing Diagnostic Accuracy in Healthcare by Using Deep Learning",
      authors: [""],
      journal: "2025 IEEE 4th World Conference on Applied Intelligence & Computing (AIC 2025)",
      year: "Nov 2025",
      description: "AI-powered system integrating deep learning and NLP for enhanced disease detection and medical report analysis.",
      status: "Published",
      type: "Conference",
      domain: "Clinical AI",
      url: "https://doi.org/10.1109/AIC66080.2025.11211920",
    },
    {
      id: "pub-polyp",
      title: "LoRA-Tuned Segment Anything Model for Few-Shot Polyp Segmentation in Colonoscopy Images",
      authors: [""],
      journal: "Journal of Carcinogenesis",
      year: "Sep 2025",
      description: "Adapts SAM for polyp segmentation with minimal labeled samples using LoRA fine-tuning, achieving high accuracy under few-shot conditions.",
      status: "Published",
      type: "Journal",
      domain: "Clinical AI",
      url: "https://doi.org/10.64149/J.Carcinog.24.3.372-386",
    },
  ],

  patents: [
    {
      id: "patent-3",
      title: "Bio-Inspired Adaptive Task Offloading System for Energy-Efficient IoT-Edge-Cloud Healthcare Continuum",
      applicationNo: "202611027418",
      country: "India",
      date: "May 2026",
      status: "Published",
      domain: "Clinical AI",
    },
    {
      id: "patent-1",
      title: "A Method for Disaster-Resilient Digital File Dissemination via Fountain-Coded Broadcast with Super-Peer Election and Sparse Acknowledgement",
      applicationNo: "202511063465",
      country: "India",
      date: "Jul 2025",
      status: "Published",
      domain: "Systems",
    },
    {
      id: "patent-2",
      title: "A Stress Monitoring System Using Wearable Sensor Data Integrated with an Ensemble Machine-Learning Model",
      applicationNo: "202511044124",
      country: "India",
      date: "May 2025",
      status: "Published",
      domain: "Clinical AI",
    },
  ],

  visitedPlaces: [
    { id: "place-1", name: "Jaipur, India", coordinates: [75.7873, 26.9124], story: "Home base", significance: "Current Location" },
    { id: "place-2", name: "Bhopal, India", coordinates: [77.401989, 23.2584857], story: "Birthplace" },
    { id: "place-4", name: "Udaipur, India", coordinates: [73.6862571, 24.578721], significance: "City of Lakes" },
    { id: "place-5", name: "New Delhi, India", coordinates: [77.2090057, 28.6138954], story: "Internship at IIIT Delhi" },
    { id: "place-6", name: "Pune, India", coordinates: [73.8544541, 18.521428], story: "Internship at Dexpert Systems" },
    { id: "place-7", name: "Ahmedabad, India", coordinates: [72.5797068, 23.0216238], story: "Exchange at IIT Gandhinagar" },
    { id: "place-8", name: "Surat, India", coordinates: [72.8317058, 21.2094892], story: "Research internship at SVNIT" },
    { id: "place-9", name: "Daman, India", coordinates: [72.833173, 20.4169701], story: "Family vacation" },
    { id: "place-10", name: "Mumbai, India", coordinates: [72.8692035, 19.054999], story: "Visited during internship" },
    { id: "place-11", name: "Lonavala, India", coordinates: [73.4016729, 18.7548563], story: "Weekend escape" },
    { id: "place-12", name: "Panaji, India", coordinates: [73.8282141, 15.4989946], story: "Family vacation" },
    { id: "place-14", name: "Munnar, India", coordinates: [77.0600915, 10.0869959], story: "Family vacation" },
    { id: "place-19", name: "Indore, India", coordinates: [75.8681996, 22.7203616], significance: "Relative's place" },
    { id: "place-22", name: "Gangtok, India", coordinates: [88.6122673, 27.329046], story: "Family vacation" },
    { id: "place-23", name: "Darjeeling, India", coordinates: [88.263176, 27.0377554], story: "Family vacation" },
    { id: "place-24", name: "Varanasi, India", coordinates: [83.0076292, 25.3356491], story: "Visited during exchange at IIT Kanpur" },
    { id: "place-25", name: "Ayodhya, India", coordinates: [82.2052321, 26.7990707], story: "Visited during exchange at IIT Kanpur" },
    { id: "place-26", name: "Kanpur, India", coordinates: [80.3217588, 26.4609135], story: "Semester exchange at IIT Kanpur" },
    { id: "place-29", name: "Noida, India", coordinates: [77.3271074, 28.5707841], story: "Internship at GeeksforGeeks" },
    { id: "place-31", name: "Chandigarh, India", coordinates: [76.7797143, 30.7334421], story: "School trip" },
    { id: "place-32", name: "Amritsar, India", coordinates: [74.8736788, 31.6343083], story: "School trip" },
    { id: "place-33", name: "Jammu, India", coordinates: [74.8580917, 32.7185614], story: "Research internship at IIT Jammu" },
    { id: "place-34", name: "Srinagar, India", coordinates: [74.8204443, 34.0747444], story: "Family vacation" },
    { id: "place-37", name: "Shimla, India", coordinates: [77.1709729, 31.1041526], story: "Family vacation" },
    { id: "place-38", name: "Manali, India", coordinates: [77.1872926, 32.2454608], story: "College trip" },
    { id: "place-39", name: "Dalhousie, India", coordinates: [75.9797487, 32.5360472], story: "School trip" },
    { id: "place-41", name: "Rishikesh, India", coordinates: [78.2916193, 30.1086537], story: "College trip" },
    { id: "place-42", name: "Nainital, India", coordinates: [79.455569, 29.3917821], story: "Family vacation" },
    { id: "place-45", name: "Kuala Lumpur, Malaysia", coordinates: [101.6942371, 3.1516964], story: "Family vacation" },
    { id: "place-49", name: "Orlando, USA", coordinates: [-81.3790304, 28.5421109], story: "Visited during travel" },
    { id: "place-50", name: "Gainesville, USA", coordinates: [-82.3249846, 29.6519684], story: "University of Florida" },
    { id: "place-55", name: "Atlanta, USA", coordinates: [-84.3902644, 33.7489924], story: "Visited during travel" },
  ],

  apis: {
    github: {
      username: "anayy09",
    },
    hashnode: {
      username: "anay09",
    },
    emailjs: {
      serviceId: process.env.REACT_APP_EMAILJS_SERVICE_ID,
      templateId: process.env.REACT_APP_EMAILJS_TEMPLATE_ID,
      publicKey: process.env.REACT_APP_EMAILJS_PUBLIC_KEY,
    },
  },
};

export default personalInfo;
